---
apiVersion: source.toolkit.fluxcd.io/v1
kind: Bucket
metadata:
  name: test-flux-bucket
  namespace: flux-system
spec:
  bucketName: test-flux
  endpoint: minio.minio-dev.svc.cluster.local:9000
  insecure: true
  interval: 1m0s
  provider: generic
  secretRef:
    name: minio-crds
